steps:
  - label: "Testing 200 OK Check"
    branches: !main
    plugins:
      - docker-compose#v3.5.0:
          run: status_check
          command: ["pytest"]

  - wait

  - label: "200 OK Check"
    plugins:
      - docker-compose#v3.5.0:
          run: status_check
